# Generated by Django 5.1.2 on 2025-01-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_registrogeral_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrogeral',
            name='sala_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
